GET http://localhost:8080/answerNotification?notification=37&answer=1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMyIsIm5hbWUiOiJ1c2VyTG9naW4xMSIsInJvbGUiOiJVU0VSIn0.Y1Y8QQyneTtl0_DTuSANcLimwUlnVEzHTXl3D1aOw-I

{
  "senderId" : 33,
  "recipientId" : 35,
  "notificationType" : 1,
  "notificationStatus" : 3
}

###



