POST http://localhost:8080/registration
Content-Type: application/json

{
"userLogin" : "ul1",
"userPassword" : "up1",
  "userFirstName" : "fn1",
  "userSecondName" : "sc1",
  "userGender" : "Male",
  "userCity" : "c1"
}

###
